#!/bin/bash

# Selfbase: Automatic Environment Setup Script
# This script generates secure random values for all secrets and creates .env file

set -e

echo "Selfbase Environment Setup"
echo "=========================="

# Check if .env already exists
if [ -f ".env" ]; then
    read -p "WARNING: .env file already exists. Overwrite? (y/N): " confirm
    if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
        echo "Aborted."
        exit 0
    fi
fi

# Generate random strings
generate_password() {
    openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 32
}

generate_jwt_secret() {
    openssl rand -base64 48 | tr -dc 'a-zA-Z0-9' | head -c 64
}

generate_secret_key() {
    openssl rand -base64 64 | head -c 64
}

# Generate JWT tokens using the secret
generate_jwt() {
    local role=$1
    local jwt_secret=$2
    
    # Header
    local header='{"alg":"HS256","typ":"JWT"}'
    local header_base64=$(echo -n "$header" | base64 -w0 | tr '+/' '-_' | tr -d '=')
    
    # Payload with role
    local payload="{\"role\":\"$role\",\"iss\":\"selfbase\",\"iat\":$(date +%s),\"exp\":$(($(date +%s) + 315360000))}"
    local payload_base64=$(echo -n "$payload" | base64 -w0 | tr '+/' '-_' | tr -d '=')
    
    # Signature
    local signature=$(echo -n "${header_base64}.${payload_base64}" | openssl dgst -sha256 -hmac "$jwt_secret" -binary | base64 -w0 | tr '+/' '-_' | tr -d '=')
    
    echo "${header_base64}.${payload_base64}.${signature}"
}

echo "Generating secure secrets..."

# Generate all secrets
POSTGRES_PASSWORD=$(generate_password)
JWT_SECRET=$(generate_jwt_secret)
DASHBOARD_PASSWORD=$(generate_password)
SECRET_KEY_BASE=$(generate_secret_key)
VAULT_ENC_KEY=$(generate_password)
PG_META_CRYPTO_KEY=$(generate_password)
POOLER_TENANT_ID=$(generate_password | head -c 16)
LOGFLARE_PUBLIC_TOKEN=$(generate_password)
LOGFLARE_PRIVATE_TOKEN=$(generate_password)

# Generate JWT tokens
echo "Generating JWT tokens..."
ANON_KEY=$(generate_jwt "anon" "$JWT_SECRET")
SERVICE_ROLE_KEY=$(generate_jwt "service_role" "$JWT_SECRET")

# Create .env file
cat > .env << EOF
############
# Secrets - Auto-generated by Selfbase setup script
# Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
############

POSTGRES_PASSWORD=$POSTGRES_PASSWORD
JWT_SECRET=$JWT_SECRET
ANON_KEY=$ANON_KEY
SERVICE_ROLE_KEY=$SERVICE_ROLE_KEY
DASHBOARD_USERNAME=admin
DASHBOARD_PASSWORD=$DASHBOARD_PASSWORD
SECRET_KEY_BASE=$SECRET_KEY_BASE
VAULT_ENC_KEY=$VAULT_ENC_KEY
PG_META_CRYPTO_KEY=$PG_META_CRYPTO_KEY


############
# Database
############

POSTGRES_HOST=db
POSTGRES_DB=postgres
POSTGRES_PORT=5432


############
# Supavisor -- Database pooler
############

POOLER_PROXY_PORT_TRANSACTION=6543
POOLER_DEFAULT_POOL_SIZE=20
POOLER_MAX_CLIENT_CONN=100
POOLER_TENANT_ID=$POOLER_TENANT_ID
POOLER_DB_POOL_SIZE=5


############
# API Proxy - Kong
############

KONG_HTTP_PORT=8000
KONG_HTTPS_PORT=8443


############
# API - PostgREST
############

PGRST_DB_SCHEMAS=public,storage,graphql_public


############
# Auth - GoTrue
############

SITE_URL=http://localhost:3000
ADDITIONAL_REDIRECT_URLS=
JWT_EXPIRY=3600
DISABLE_SIGNUP=false
API_EXTERNAL_URL=http://localhost:8000

## Email auth
ENABLE_EMAIL_SIGNUP=true
ENABLE_EMAIL_AUTOCONFIRM=true
SMTP_ADMIN_EMAIL=admin@example.com
SMTP_HOST=selfbase-mail
SMTP_PORT=2500
SMTP_USER=fake_mail_user
SMTP_PASS=fake_mail_password
SMTP_SENDER_NAME=Selfbase
ENABLE_ANONYMOUS_USERS=false

## Phone auth
ENABLE_PHONE_SIGNUP=true
ENABLE_PHONE_AUTOCONFIRM=true


############
# Studio
############

SUPABASE_PUBLIC_URL=http://localhost:8000

# Enable webp support
IMGPROXY_ENABLE_WEBP_DETECTION=true

# OpenAI API key for SQL Assistant (optional)
OPENAI_API_KEY=


############
# Functions
############

FUNCTIONS_VERIFY_JWT=false


############
# Logs - Analytics
############

LOGFLARE_PUBLIC_ACCESS_TOKEN=$LOGFLARE_PUBLIC_TOKEN
LOGFLARE_PRIVATE_ACCESS_TOKEN=$LOGFLARE_PRIVATE_TOKEN

# Docker socket location
DOCKER_SOCKET_LOCATION=/var/run/docker.sock

# Google Cloud Project details (optional)
GOOGLE_PROJECT_ID=
GOOGLE_PROJECT_NUMBER=
EOF

echo ""
echo "Environment setup complete!"
echo ""
echo "Generated credentials:"
echo "   Dashboard Username: admin"
echo "   Dashboard Password: $DASHBOARD_PASSWORD"
echo ""
echo "Start Selfbase with:"
echo "   docker compose up -d"
echo ""
